### PR TITLE
Add phpstan to clean code

### PR DESCRIPTION
**Pull request by notFloran**
Use phpstan to clean code. With the level 5 4 errors are found but these errors came from the compatibility layer (#21).

### CODE REVIEW

**Comment by nclsHart** [comment]
LGTM. I just wait #20 be merged to merge this one.

**Comment by nclsHart** [comment]
@notFloran Could you rebase with latest changes?

**Comment by notFloran** [comment]
Active supports for php 7.0 ends at the end of the year, so like SF4 I remove php 7.0 as a supported version.

What do you think @nclsHart ?

**Comment by notFloran** [comment]
@nclsHart build is now ok

**Review by nclsHart — APPROVED** [review]
I think this is ok. PHP 7.0 users will still be able to use branch 1.x.

**Pull request merged**
